### ISSUE TITLE
imapcli list UnicodeEncodeError

### ISSUE THREAD

**Issue by mndrix** [Gentux/imap-cli#14]
I run `imapcli list inbox` and see 14 messages as expected.  I run `imapcli list inbox --format="{uid:7} {subject}"` and see 8 messages then this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/imap-cli-list", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/imap_cli/list_mail.py", line 78, in main
    display_conf['format_list'].format(**mail_info))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 10: ordinal not in range(128)
```

The offending message has the following subject:

```
A special “Thank you” from families you blessed last year
```

Do I need to do something special to format subjects with Unicode?

**Comment by xiconet** [comment]
Hi,
Before all, thank you for providing code free of charge.
I have a similar encoding/decoding problem with the `imap-shell` , with python 2.7 on the "old", "obsolete", "insecure" but stable WinXP-SP3.
When running `list`:
```python
 'charmap' codec can't encode character u'\u2013' in position 95: character maps to <undefined> 
```

**Comment by Gentux** [comment]
Thank you verry much for the report.

I can't fix it right now because I'm in a foreign country with a poor internet connection.

I'll dig into it when I get back home. Feel free to post a pull request if you have the time :)
