### ISSUE TITLE
Parsing email list broken with python3

### ISSUE THREAD

**Issue by Gentux** [Gentux/imap-cli#18]
Imap-CLI use *ast* module to parse imap result and this method does not work with python3.

**Comment by malikbenkirane** [comment]
Peut-etre [ici](https://github.com/Gentux/imap-cli/blob/10310556a4215a0b10d5b825743aac3dc5d73c36/imap_cli/search.py#L387) ?

**Comment by Gentux** [comment]
Exactly :)
I think we need to write a real parser here

**Comment by Gentux** [comment]
I can't fully test this solution right now. If you can, please take a look at PR #19

**Comment by Gentux** [comment]
Solved \o/ 🎉
