### ISSUE TITLE
SASL XOAUTH2 support

### ISSUE THREAD

**Issue by mathewmarcus** [Gentux/imap-cli#23]
Would you be interested in a pull request to add support for different methods of authentication, such as the [SASL XOAUTH2 mechanism](https://developers.google.com/gmail/imap/xoauth2-protocol#the_sasl_xoauth2_mechanism) used by Gmail?

**Comment by Gentux** [comment]
Yeah, totally !

I'm not using gmail so I can't tell if it's working or not.
Thank you
